#!/usr/bin/env bash
# Summary: Write a Java version to a version file
# Usage: barista version-file-write <file> <version>

set -e
[ -n "$BARISTA_DEBUG" ] && set -x

version_file="$1"
version="$2"

if [ -z "$version_file" ] || [ -z "$version" ]; then
  echo "Usage: barista version-file-write <file> <version>" >&2
  exit 1
fi

echo "$version" > "$version_file"
