#!/usr/bin/env bash
# Summary: Display help for a barista command
# Usage: barista help [<command>]
#
# With no arguments, shows a summary of all commands.
# With a command name, prints its full usage documentation.

set -e
[ -n "$BARISTA_DEBUG" ] && set -x

if [ -z "$BARISTA_DIR" ]; then
  BARISTA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
fi

extract_header_comments() {
  sed -ne '/^#/!q;s/^#$/# /;/^# /p' < "$1" | sed -E 's/^# ?//'
}

print_summary() {
  extract_header_comments "$1" | grep '^Summary:' | sed 's/^Summary: //'
}

command="$1"
if [ -z "$command" ]; then
  echo "Usage: barista <command> [<args>]"
  echo
  echo "Java version management, barista-style."
  echo
  echo "Commands:"
  shopt -s nullglob
  for cmd_file in "${BARISTA_DIR}/execs/barista-"*; do
    cmd="${cmd_file##*/barista-}"
    case "$cmd" in
    sh-* | version-file-read | version-file-write ) continue ;;
    esac
    summary="$(print_summary "$cmd_file")"
    printf "   %-20s  %s\n" "$cmd" "$summary"
  done | sort
  exit 0
fi

command_file="${BARISTA_DIR}/execs/barista-${command}"
if [ ! -e "$command_file" ]; then
  echo "barista: no such command '$command'" >&2
  exit 1
fi

extract_header_comments "$command_file"
